Repository PlaceOS/drivers, pull requests merged in 2021-08, with the labels that each got.

#166 Svsi
  drivers/amx/svsi/n_series_decoder.cr
  drivers/amx/svsi/n_series_encoder.cr
  drivers/amx/svsi/n_series_switcher.cr
  drivers/amx/svsi/virtual_switcher.cr
Labels: type: migrate driver

#201 feat(staff_api): add approved param
  drivers/place/staff_api.cr
Labels: type: enhancement

#223 Update LICENSE
  LICENSE
Labels: type: documentation

#235 feat(meraki/locations): Apply device OS filter to list of Locations too
  drivers/cisco/meraki/meraki_locations.cr
Labels: type: enhancement

#236 Feat/meraki/location/device filter
  drivers/cisco/meraki/meraki_locations.cr
Labels: type: bug

#239 chore(harness): crystal 1.1.1 instead of 1.0.0
  docker-compose.yml
Labels: priority: low, type: enhancement
