Repository PlaceOS/drivers, pull requests merged in 2021-04, with the labels that each got.

#24 Lenel OpenAccess driver
  drivers/lenel/open_access.cr
  drivers/lenel/open_access/client.cr
  drivers/lenel/open_access/error.cr
  drivers/lenel/open_access/models.cr
  drivers/lenel/open_access_spec.cr
  shard.lock
  shard.yml
Labels: type: driver, type: migrate driver

#134 build(docker-compose): remove the container_name key for redis
  docker-compose.yml
Labels: focus: devops, type: enhancement

#128 Sony LCD
  drivers/sony/displays/bravia.cr
  drivers/sony/displays/bravia_spec.cr
Labels: type: driver

#138 fix(sony/projector): fix bug in rendering bytes
  drivers/sony/projector/serial_control.cr
Labels: type: bug

#145 chore(shard.lock): bump calendar and office365
  shard.lock
Labels: priority: high

#135 build: bump to placeos-driver 5.0.8
  shard.lock
  shard.yml
Labels: priority: critical, type: bug

#149 style: define base ameba config and fix lints across drivers
  .ameba.yml
  drivers/cisco/dna_spaces.cr
  drivers/cisco/meraki/dashboard.cr
  drivers/cisco/meraki/meraki_locations.cr
  drivers/cisco/meraki/meraki_locations_spec.cr
  drivers/cisco/switch/snooping_catalyst.cr
  drivers/denon/amplifier/av_receiver.cr
  drivers/extron/matrix.cr
  drivers/floorsense/bookings_sync.cr
  drivers/floorsense/location_service.cr
  drivers/lenel/open_access.cr
  drivers/lenel/open_access/client.cr
  drivers/lenel/open_access/error.cr
  drivers/lenel/open_access_spec.cr
  drivers/microsoft/find_me_spec.cr
  drivers/mulesoft/booking_api.cr
  drivers/mulesoft/booking_api_spec.cr
  drivers/place/calendar.cr
  drivers/screen_technics/connect.cr
  drivers/vergesense/vergesense_api.cr
  drivers/xovis/sensor_api.cr
  drivers/xovis/sensor_api_spec.cr
  drivers/xy_sense/location_service.cr
  shard.lock
  shard.yml
Labels: type: enhancement, type: maintenance
