Repository PlaceOS/drivers, pull requests merged in 2022-05, with the labels that each got.

#312 style: maintain docs and fix repository ameba failures
  .ameba.yml
  .github/workflows/ci.yml
  README.md
  docker-compose.yml
  docs/directory_structure.md
  docs/guide-event-emails.md
  docs/setup.md
  docs/writing-a-driver.md
  docs/writing-a-spec.md
  drivers/ashrae/bacnet.cr
  drivers/cisco/meraki/mqtt.cr
  drivers/cisco/ui_extender.cr
  drivers/cisco/webex/client.cr
  drivers/cisco/webex/session.cr
  drivers/extron/matrix.cr
  drivers/lenel/open_access.cr
  drivers/lutron/vive_leap.cr
  drivers/mulesoft/calendar_exporter.cr
  drivers/panasonic/camera/he_series.cr
  drivers/place/router/digraph.cr
  drivers/place/router/settings.cr
  drivers/place/router/signal_graph.cr
  drivers/shure/microphone/mxa.cr
  drivers/webex/instant_connect.cr
  drivers/xy_sense/location_service_spec.cr
Labels: status: blocked, type: maintenance

#327 feat(staff-api): add merge metadata method
  drivers/place/staff_api.cr
  shard.lock
Labels: type: enhancement

#238 feat: build
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .gitignore
  README.md
  docker-compose.yml
  drivers/amx/svsi/n_series_decoder.cr
  drivers/amx/svsi/n_series_encoder.cr
  drivers/amx/svsi/n_series_switcher.cr
  drivers/cisco/meraki/mqtt.cr
  drivers/cisco/meraki/mqtt_spec.cr
  drivers/cisco/webex_bot.cr
  drivers/cisco/webex_bot_spec.cr
  drivers/mulesoft/calendar_exporter.cr
  drivers/place/calendar.cr
  drivers/place/mqtt_spec.cr
  drivers/vergesense/mqtt_export.cr
  drivers/webex/instant_connect.cr
  drivers/webex/instant_connect_spec.cr
  harness
  shard.lock
Labels: priority: high, type: refactor, type: enhancement, type: new feature
